# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Acceptable Albatrosses

on:
    - push
    - pull_request

jobs:
    linting:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install dependencies and setup
              env:
                  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install pipenv
                  cd acceptable-albatrosses
                  echo DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY > .env
                  pipenv install --dev
            - name: Lint with flake8
              if: ${{ always() }}
              run: |
                  cd acceptable-albatrosses
                  # stop the build if there are Python syntax errors or undefined names
                  pipenv run flake8 albatrosses_hub --count --select=E9,F63,F7,F82 --show-source --statistics
                  pipenv run flake8 albatrosses_hub --count --statistics
            - name: Lint with mypy (typing)
              if: ${{ always() }}
              run: |
                  cd acceptable-albatrosses
                  pipenv run mypy albatrosses_hub
            - name: Lint with pylint
              if: ${{ always() }}
              run: |
                  cd acceptable-albatrosses
                  pipenv run pylint albatrosses_hub/**/*.py
            - name: Lint with black (formatting)
              if: ${{ always() }}
              run: |
                  cd acceptable-albatrosses
                  pipenv run black albatrosses_hub --check -l 119
